"""Shared configuration: branch registry, desk services, and calendar constants.

Branch coordinates and the desk-service taxonomy are loaded at import time
from files generated by the real-data pipeline:
  - data/branches_registry.json  (pipeline/geocode_branches.py) — 78 real
    Loja de Cidadão stores from dados.gov.pt, geocoded via Nominatim. Most
    resolved at store-name precision; some fall back to municipality-center
    precision (see each branch's `geocode_precision`), which is a real but
    coarser approximation.
  - data/known_desk_services.csv (pipeline/load_historical.py) — the real,
    lightly-cleaned set of service labels observed in the dataset.

If either file is missing (e.g. a fresh checkout before the ingestion
pipeline has run), this module falls back to a small hardcoded placeholder
set so the rest of the app still imports and runs.

`siga_url` values are always placeholders — swap in each branch's real SIGA
status endpoint once confirmed with AMA / ePortugal; the live-polling
scraper's exact selectors are unverified regardless of coordinate source.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path

BRANCH_REGISTRY_PATH = "data/branches_registry.json"
KNOWN_SERVICES_PATH = "data/known_desk_services.csv"


@dataclass(frozen=True)
class Branch:
    branch_id: str
    name: str
    district: str
    latitude: float
    longitude: float
    siga_url: str
    desk_service_ids: tuple[str, ...]
    municipality: str = ""
    geocode_precision: str = "unknown"


# --------------------------------------------------------------------------
# Placeholder fallback (used only if the generated registry files are absent)
# --------------------------------------------------------------------------

_PLACEHOLDER_DESK_SERVICES: tuple[str, ...] = (
    "cartao_cidadao",
    "financas",
    "seguranca_social",
    "registo_civil",
    "iban_bancario",
)

_PLACEHOLDER_BRANCHES: tuple[Branch, ...] = (
    Branch(
        branch_id="lisboa_laranjeiras",
        name="Loja de Cidadão - Laranjeiras",
        district="Lisboa",
        latitude=38.7452,
        longitude=-9.1662,
        siga_url="https://siga.lojadocidadao.pt/status/lisboa_laranjeiras",
        desk_service_ids=_PLACEHOLDER_DESK_SERVICES,
    ),
    Branch(
        branch_id="lisboa_baixa",
        name="Loja de Cidadão - Baixa-Chiado",
        district="Lisboa",
        latitude=38.7107,
        longitude=-9.1391,
        siga_url="https://siga.lojadocidadao.pt/status/lisboa_baixa",
        desk_service_ids=_PLACEHOLDER_DESK_SERVICES,
    ),
    Branch(
        branch_id="porto_baixa",
        name="Loja de Cidadão - Porto Baixa",
        district="Porto",
        latitude=41.1496,
        longitude=-8.6109,
        siga_url="https://siga.lojadocidadao.pt/status/porto_baixa",
        desk_service_ids=_PLACEHOLDER_DESK_SERVICES,
    ),
)


def _load_branches_from_registry(path: str) -> tuple[Branch, ...] | None:
    registry_path = Path(path)
    if not registry_path.exists():
        return None
    raw_branches = json.loads(registry_path.read_text())
    return tuple(
        Branch(
            branch_id=entry["branch_id"],
            name=entry["name"],
            district=entry["district"],
            municipality=entry.get("municipality", ""),
            latitude=entry["latitude"],
            longitude=entry["longitude"],
            siga_url=f"https://siga.lojadocidadao.pt/status/{entry['branch_id']}",
            desk_service_ids=tuple(entry.get("desk_service_ids", [])),
            geocode_precision=entry.get("geocode_precision", "unknown"),
        )
        for entry in raw_branches
    )


def _load_desk_services_from_csv(path: str) -> tuple[str, ...] | None:
    services_path = Path(path)
    if not services_path.exists():
        return None
    with services_path.open(newline="") as handle:
        return tuple(row["service_type"] for row in csv.DictReader(handle))


_loaded_branches = _load_branches_from_registry(BRANCH_REGISTRY_PATH)
_loaded_services = _load_desk_services_from_csv(KNOWN_SERVICES_PATH)

BRANCHES: tuple[Branch, ...] = _loaded_branches if _loaded_branches else _PLACEHOLDER_BRANCHES
DESK_SERVICES: tuple[str, ...] = _loaded_services if _loaded_services else _PLACEHOLDER_DESK_SERVICES
USING_REAL_BRANCH_REGISTRY: bool = _loaded_branches is not None

BRANCHES_BY_ID: dict[str, Branch] = {branch.branch_id: branch for branch in BRANCHES}

# Average minutes to service one ticket, per desk service. Used to convert a
# raw "people waiting" count into an estimated wait time when the SIGA page
# does not directly expose a wait-time figure, and as a fallback default for
# any of the real dataset's ~200 service labels not listed here explicitly.
# A handful of the most common real services are annotated for realism; the
# rest use DEFAULT_SERVICE_AVG_MINUTES.
DEFAULT_SERVICE_AVG_MINUTES = 10.0
SERVICE_AVG_MINUTES: dict[str, float] = {
    "Atendimento Geral": 8.0,
    "Cartão de Cidadão - Pedido/Renovação": 12.0,
    "Cartão de Cidadão - Levantamento": 5.0,
    "Cartão de Cidadão - Outros": 8.0,
    "Carta de Condução/ Driving License": 15.0,
    "Registo veículos - Pedido": 12.0,
    "Passaporte - Pedido": 15.0,
    "Passaporte - Levantamento / Inf.": 5.0,
    "Registo Predial - Certidões / Inf.": 10.0,
    "Registo Civil - Certidões / Inf.": 10.0,
    "Tesouraria": 6.0,
    "Execuções Fiscais": 18.0,
    "Marcação": 4.0,
    # Placeholder-registry service ids, kept so synthetic_bootstrap.py still
    # works when the real registry files are absent.
    "cartao_cidadao": 12.0,
    "financas": 15.0,
    "seguranca_social": 18.0,
    "registo_civil": 10.0,
    "iban_bancario": 8.0,
}

# Recurring annual tax deadlines as (month, day) tuples.
IRS_DEADLINE_MONTH_DAY: tuple[int, int] = (6, 30)
IMI_DEADLINE_MONTHS_DAYS: tuple[tuple[int, int], ...] = ((5, 31), (8, 31), (11, 30))

DEFAULT_DB_PATH = "data/queue_history.db"
DEFAULT_MODEL_PATH = "models/xgboost_wait_time.joblib"

# Baseline statistical fallback used when no model/feature data is available.
BASELINE_WAIT_MINUTES = 20.0
BASELINE_RAIN_MM = 0.0
BASELINE_ATTENDANCES = 10.0  # roughly the observed median daily attendances/store/service

REROUTE_RADIUS_KM = 15.0

# Fallback assumed business hours, used only when no real is_open signal is
# available (see NEAR_NOW_WINDOW_MINUTES below) — no real per-branch schedule
# data exists anywhere yet. Once scrapers/siga_scraper.py has accumulated
# enough real is_open observations per branch, this heuristic should be
# replaced with an actual observed schedule.
ASSUMED_BUSINESS_HOUR_START = 9
ASSUMED_BUSINESS_HOUR_END = 17
ASSUMED_BUSINESS_DAYS = frozenset({0, 1, 2, 3, 4})  # Mon-Fri, per datetime.weekday()

# Extra surge_level value (alongside "low"/"moderate"/"high"/"critical") used
# when the branch is known/assumed closed. Deliberately reuses the existing
# surge_level field rather than adding a new response field, so the
# /predict response schema (predicted_wait_minutes, surge_level,
# confidence_score, recommended_alternative_store) never changes shape.
SURGE_CLOSED_LABEL = "closed"

# "Latest known people_waiting" only means something for a "what's the queue
# like right now" request. If the requested prediction datetime is far from
# actual wall-clock now (a different hour of day, or a future/past date),
# reusing the single most-recent DB reading pairs a stale queue-state value
# with an unrelated hour_of_day/calendar context the model never saw
# together in training — an out-of-distribution combination that produces
# unstable, sometimes wildly extrapolated predictions (observed: negative
# and >2x-the-training-cap outputs for the same combo at different
# requested hours, all sharing one stale people_waiting reading). Beyond
# this window, people_waiting falls back to baseline instead.
NEAR_NOW_WINDOW_MINUTES = 60

# Real SIGA `tempoRealEspera` readings are sometimes wildly implausible —
# found 2026-07-27: 46% of "open" readings from one scheduled scrape showed
# 180-13,366 minutes, uncorrelated with the actual people_waiting count (many
# showed 0 people waiting alongside a 5-figure "wait"). Working hypothesis:
# the field may reflect elapsed idle time since the counter was last used,
# not a live computed wait — unconfirmed. A real physical queue cannot
# outlast a single business day before the branch closes and tickets reset,
# so anything above this is treated as implausible and excluded from the
# `estimated_wait_minutes` field used by training/API — but the untouched
# raw value is always kept in `raw_wait_time_minutes` so this can still be
# investigated later without having lost the original signal. Deliberately
# not reusing MAX_DERIVED_WAIT_MINUTES (180) here — that number was chosen
# for a synthetic queueing formula's assumptions, not a real-world constraint.
REAL_DATA_MAX_PLAUSIBLE_WAIT_MINUTES = 480

# Found 2026-07-30: the flat 480-min ceiling above still let contaminated
# readings through just under it. Diagnosed via pipeline.train's held-out
# residuals on siga_live -- the 20 worst prediction misses all had actual
# labels of 387-480 min (right against the ceiling) with 0-4 people
# actually waiting, and abs(residual) correlated with raw_wait_time_minutes
# at 0.745 but with people_waiting at only 0.169. Checked across the full
# corpus, not just the tail: of 931 rows with wait_time_minutes >= 300,
# 88.3% had people_waiting <= 1. Comparing each reading to the same
# (branch, service)'s immediately preceding poll confirmed two distinct
# failure modes, not one: ~55% of >=300min readings are frozen (delta <=5
# min despite ~15-30 real minutes elapsed -- a stale/stuck value carrying
# zero new information), and the rest show an erratic tail (deltas up to
# +-18,000 min between polls 20-40 min apart -- physically impossible for
# a real ticket queue, which even accounting for people stepping out and
# returning cannot swing that fast). Neither pattern is consistent with a
# genuine measurement of something people_waiting merely doesn't capture.
# pipeline/db.py's clean_siga_live_readings() uses these two constants
# to drop frozen repeats (true information loss: zero, since a stuck value
# adds nothing beyond the already-kept prior reading) and clamp -- not
# discard -- the erratic tail to a plausible bound, so a corrected data
# point survives instead of being thrown away. Only checked/applied at
# wait_time_minutes >= this threshold: freezing at a low value (e.g. two
# consecutive genuine 0-min readings) is mundane and real, not a bug
# signal -- restricting to the regime where the pathology was actually
# found avoids discarding legitimate quiet periods.
SIGA_STALENESS_CHECK_MIN_WAIT_MINUTES = 300
# Two consecutive polls of the same (branch, service) are only compared if
# no more than this many real minutes elapsed -- guards against comparing
# across a multi-hour or multi-day scraper gap (e.g. an overnight or
# outage gap), where a "no change" or big swing is expected and meaningless
# for staleness/erratic-rate detection. ~2x the ~15-20 min steady-state
# sweep cadence as of 2026-07-30, generous enough to tolerate a missed tick.
SIGA_STALENESS_CHECK_MAX_GAP_MINUTES = 40
# Deliberately generous (not a tight physical model): a real wait dropping
# steadily as tickets are served, or rising during a rush, stays well under
# this. Chosen to only catch the clearly-impossible tail found above (ratios
# of hundreds-to-thousands of minutes of "change" per minute of real elapsed
# time) while leaving ordinary real dynamics untouched -- minimizing false
# positives over catching every last erratic point.
SIGA_MAX_PLAUSIBLE_WAIT_CHANGE_PER_MINUTE = 10.0

# --------------------------------------------------------------------------
# Wait-time proxy derivation (pipeline/demand_baseline.py)
#
# The real dados.gov.pt dataset has no desk-count or intra-day field, so
# converting its daily Atendimentos counts into an approximate wait_time_minutes
# requires assuming a number of parallel desks and a business-day length. These
# are documented simplifications, not measured facts — tune them if better
# information becomes available (e.g. per-store desk counts).
# --------------------------------------------------------------------------
DEFAULT_DESKS_PER_SERVICE = 3
OPERATING_HOURS_PER_DAY = 8.0
MAX_DERIVED_WAIT_MINUTES = 180.0

# A single flat desk count badly understates capacity for the handful of
# real combos with extreme volume (some real branch/service pairs exceed
# 900 attendances/day for one service) — pipeline/demand_baseline.py scales
# the assumed desk count up with real daily volume and this service's own
# avg_service_minutes (see estimate_desks_for_volume), using DEFAULT_DESKS_PER_SERVICE
# only as a floor for low-volume combos. TARGET_DESK_UTILIZATION is the
# sustainable fraction of full capacity a desk is assumed to run at.
TARGET_DESK_UTILIZATION = 0.7

# --------------------------------------------------------------------------
# Intraday expansion for derived proxy rows (pipeline/demand_baseline.py)
#
# The real dataset has no intra-day timestamp, so anchoring every daily
# proxy row at one flat clock time would give `hour_of_day` zero variance
# across the entire proxy dataset. Instead each day is expanded into
# representative daypart snapshots: (hour, minute, volume_factor), where
# volume_factor scales the day's average hourly attendance rate (factors
# average to 1.0 across a "typical" day). Each snapshot's wait-time estimate
# uses SNAPSHOT_WINDOW_HOURS (~1 hour), not the full day, as the M/M/1
# capacity window, since a snapshot represents an hour-scale slice of
# demand, not the whole day's total — reusing the full-day operating-hours
# constant here would make capacity look ~8x too large and understate wait
# times at every snapshot.
#
# Densified from 3 to 8 (one per business hour, 9:30-16:30, matching
# OPERATING_HOURS_PER_DAY=8.0) on 2026-07-27: with only 3 anchors, a
# same-week day-of-week ranking that was correct at 12:30 came out
# scrambled at 10-11am on the identical branch/service — the model had
# real support at exactly 3 clock times and was extrapolating everywhere
# else. This is still a documented approximation, not measured ground
# truth (a bell-ish ramp-up/peak/wind-down shape), just at finer
# resolution than before.
#
# !! OPEN FINDING (2026-07-30): REAL DATA SUGGESTS THIS CURVE IS INVERTED.
# The first real intra-day evidence this project has ever had -- live SIGA
# `people_waiting` counts, which (unlike tempoRealEspera) show no sign of
# the stale-counter pathology -- disagrees with the shape below, strongly.
# Normalized per (branch, service) to remove composition bias, across 71
# branches, by LOCAL (Europe/Lisbon) hour:
#     hour   assumed   observed
#      9      0.70      1.33
#     10      0.85      1.67   <- real peak
#     11      1.00      1.39
#     12      1.35      0.88
#     13      1.35      0.63   <- real trough
#     14      1.10      0.72
# Pearson correlation between assumed and observed: -0.79. The assumed
# peak (12-13h) is close to the observed *quietest* hour. Ask the model
# "what's the best hour to go" today and it will confidently recommend
# roughly the busiest real time, because this curve is what generated the
# hour_of_day signal in ~6.9M historical_derived_proxy training labels --
# so it is baked into the bulk of the training data, not just inference.
#
# NOT yet acted on, deliberately: only ~3 days of live data back this, and
# one innocent explanation isn't ruled out -- a midday dip in
# `people_waiting` could reflect staff lunch breaks cutting capacity
# rather than genuinely lower demand (the factors below are meant to
# represent demand volume). Recalibrating is also high-blast-radius: it
# regenerates every proxy label (pipeline/demand_baseline.py) and would
# invalidate the fitted output of pipeline/calibrate_constants.py, which
# was calibrated against labels built from the current factors. Revisit
# once several more weeks of live coverage exist; recalibrate against real
# people_waiting rather than re-guessing the shape by hand.
# --------------------------------------------------------------------------
DIURNAL_SNAPSHOTS: tuple[tuple[int, int, float], ...] = (
    (9, 30, 0.70),   # opening ramp-up
    (10, 30, 0.85),
    (11, 30, 1.00),
    (12, 30, 1.35),  # midday peak
    (13, 30, 1.35),  # midday peak continues
    (14, 30, 1.10),
    (15, 30, 0.85),
    (16, 30, 0.80),  # closing wind-down
)
SNAPSHOT_WINDOW_HOURS = 1.0

# --------------------------------------------------------------------------
# Proxy-vs-live sample weighting (pipeline/train.py)
#
# Once live SIGA scraping accumulates real samples for a given
# (branch_id, desk_service_id), that combo's historical_derived_proxy rows
# should count for less during training — but a global "drop all proxy data"
# cutover is wrong: real coverage will be extremely uneven across ~2,000
# distinct combos, so a global switch would blind whichever combos haven't
# accumulated live data yet. Instead each proxy row's weight decays per its
# own combo's live sample count: w = 1 / (1 + alpha * live_count). At
# live_count=0 (true today — no live scraping has run yet) w=1.0, i.e. this
# is a no-op until live data actually exists.
#
# RAISED 0.05 -> 0.5 on 2026-07-31, because 0.05 was far too weak to matter.
# Measured at that point: siga_live held 39,904 rows against 6.89M proxy
# rows, so despite carrying weight 1.0 per row it was **0.77% of total
# training weight**. The model was being fit toward a weighted mean target
# of 5.53 min while real live waits averaged 44.53 — and a forward test
# (pipeline/forward_test.py) showed exactly that signature: predicted mean
# 28.5 against an actual 41.2, i.e. systematic under-prediction, which for
# a citizen-facing wait estimate is the more damaging direction of error.
#
# The decay was too slow to bite at ANY realistic coverage level. On the
# best-covered combo in the whole dataset (65 live samples) a proxy row had
# still only decayed to 0.235, leaving proxy outweighing live 19:1 there.
# That also explains why the under-prediction looked uniform across
# well-covered and sparse combos alike — proxy dominates both, so uniformity
# was evidence FOR proxy dominance, not against it.
#
# 0.5 brings that same best-covered combo to roughly 2.4:1 rather than
# flipping it live-dominant — deliberately conservative, since ~30% of live
# readings are still of questionable quality (see
# REAL_DATA_MAX_PLAUSIBLE_WAIT_MINUTES above) and should not be trusted to
# outvote everything else outright.
#
# WHY THIS IS SAFE FOR LOW-COVERAGE COMBOS, which is the obvious worry:
# weight is 1/(1 + alpha*live_count), so a combo with zero live samples
# keeps weight exactly 1.0 for ANY alpha. Raising alpha can only ever affect
# combos that have earned real coverage — it is not a global down-weighting,
# and the ~1,500 combos relying solely on proxy data are untouched by
# construction. pipeline/forward_test.py's coverage split exists to verify
# that invariant empirically after any change here: the sparse segment must
# come out unchanged.
# --------------------------------------------------------------------------
PROXY_WEIGHT_DECAY_ALPHA = 0.5

# --------------------------------------------------------------------------
# historical_real_daily_avg reliability weighting (pipeline/train.py)
#
# IALC-M branch-day averages (pipeline/ingest_real_wait_times.py) are real
# measurements, but some branch-days carry very low Total_Atendimentos
# (occasionally 1 — see the SLC-M/IALC-M cross-check, 2026-07-27), making
# that day's "average" a single noisy raw reading rather than a stable mean.
# Each row's weight is sample_size / (sample_size + REFERENCE) — a smooth
# 0->1 curve reaching 0.5 at REFERENCE attendances. 30 reuses the same
# "meaningfully covered" threshold already established for siga_live combos
# (pipeline/coverage_report.py's --min-samples default), rather than
# introducing an unrelated new number.
# --------------------------------------------------------------------------
HISTORICAL_REAL_AVG_REFERENCE_SAMPLE_SIZE = 30

# --------------------------------------------------------------------------
# Snapshot-proximity confidence discount (api/service.py)
#
# Found 2026-07-27: the bulk of training labels (historical_derived_proxy
# AND historical_real_daily_avg) only existed at DIURNAL_SNAPSHOTS' three
# anchor times (9:30/12:30/15:30) — away from those, the model had far less
# real support and its predictions were materially less reliable (a
# same-week day-of-week ranking that looked sensible at 12:30 came out
# scrambled at 10-11am on the same branch/service). confidence_score
# discounts requests whose target hour falls outside
# SNAPSHOT_PROXIMITY_MINUTES of the nearest anchor, same as it already
# discounts for other missing/stale signals.
#
# THIS THRESHOLD SCALES WITH ANCHOR SPACING, NOT A FIXED NUMBER: DIURNAL_
# SNAPSHOTS was later densified to 8 hourly anchors (60 min apart) — with
# the old 30-minute threshold, EVERY in-business-hours query would sit
# within it (max possible distance to the nearest hourly anchor is exactly
# 30 min, at the midpoint between two anchors), silently turning this
# discount into dead code. Kept at roughly 1/6 of the anchor spacing, same
# ratio as when spacing was 3 hours and the threshold was 30 min.
# --------------------------------------------------------------------------
SNAPSHOT_PROXIMITY_MINUTES = 10
SNAPSHOT_DISTANCE_CONFIDENCE_PENALTY = 0.15
