"""Shared configuration: branch registry, desk services, and calendar constants.

Branch coordinates and the desk-service taxonomy are loaded at import time
from files generated by the real-data pipeline:
  - data/branches_registry.json  (pipeline/geocode_branches.py) — 78 real
    Loja de Cidadão stores from dados.gov.pt, geocoded via Nominatim. Most
    resolved at store-name precision; some fall back to municipality-center
    precision (see each branch's `geocode_precision`), which is a real but
    coarser approximation.
  - data/known_desk_services.csv (pipeline/load_historical.py) — the real,
    lightly-cleaned set of service labels observed in the dataset.

If either file is missing (e.g. a fresh checkout before the ingestion
pipeline has run), this module falls back to a small hardcoded placeholder
set so the rest of the app still imports and runs.

`siga_url` values are always placeholders — swap in each branch's real SIGA
status endpoint once confirmed with AMA / ePortugal; the live-polling
scraper's exact selectors are unverified regardless of coordinate source.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path

BRANCH_REGISTRY_PATH = "data/branches_registry.json"
KNOWN_SERVICES_PATH = "data/known_desk_services.csv"


@dataclass(frozen=True)
class Branch:
    branch_id: str
    name: str
    district: str
    latitude: float
    longitude: float
    siga_url: str
    desk_service_ids: tuple[str, ...]
    municipality: str = ""
    geocode_precision: str = "unknown"


# --------------------------------------------------------------------------
# Placeholder fallback (used only if the generated registry files are absent)
# --------------------------------------------------------------------------

_PLACEHOLDER_DESK_SERVICES: tuple[str, ...] = (
    "cartao_cidadao",
    "financas",
    "seguranca_social",
    "registo_civil",
    "iban_bancario",
)

_PLACEHOLDER_BRANCHES: tuple[Branch, ...] = (
    Branch(
        branch_id="lisboa_laranjeiras",
        name="Loja de Cidadão - Laranjeiras",
        district="Lisboa",
        latitude=38.7452,
        longitude=-9.1662,
        siga_url="https://siga.lojadocidadao.pt/status/lisboa_laranjeiras",
        desk_service_ids=_PLACEHOLDER_DESK_SERVICES,
    ),
    Branch(
        branch_id="lisboa_baixa",
        name="Loja de Cidadão - Baixa-Chiado",
        district="Lisboa",
        latitude=38.7107,
        longitude=-9.1391,
        siga_url="https://siga.lojadocidadao.pt/status/lisboa_baixa",
        desk_service_ids=_PLACEHOLDER_DESK_SERVICES,
    ),
    Branch(
        branch_id="porto_baixa",
        name="Loja de Cidadão - Porto Baixa",
        district="Porto",
        latitude=41.1496,
        longitude=-8.6109,
        siga_url="https://siga.lojadocidadao.pt/status/porto_baixa",
        desk_service_ids=_PLACEHOLDER_DESK_SERVICES,
    ),
)


def _load_branches_from_registry(path: str) -> tuple[Branch, ...] | None:
    registry_path = Path(path)
    if not registry_path.exists():
        return None
    raw_branches = json.loads(registry_path.read_text())
    return tuple(
        Branch(
            branch_id=entry["branch_id"],
            name=entry["name"],
            district=entry["district"],
            municipality=entry.get("municipality", ""),
            latitude=entry["latitude"],
            longitude=entry["longitude"],
            siga_url=f"https://siga.lojadocidadao.pt/status/{entry['branch_id']}",
            desk_service_ids=tuple(entry.get("desk_service_ids", [])),
            geocode_precision=entry.get("geocode_precision", "unknown"),
        )
        for entry in raw_branches
    )


def _load_desk_services_from_csv(path: str) -> tuple[str, ...] | None:
    services_path = Path(path)
    if not services_path.exists():
        return None
    with services_path.open(newline="") as handle:
        return tuple(row["service_type"] for row in csv.DictReader(handle))


_loaded_branches = _load_branches_from_registry(BRANCH_REGISTRY_PATH)
_loaded_services = _load_desk_services_from_csv(KNOWN_SERVICES_PATH)

BRANCHES: tuple[Branch, ...] = _loaded_branches if _loaded_branches else _PLACEHOLDER_BRANCHES
DESK_SERVICES: tuple[str, ...] = _loaded_services if _loaded_services else _PLACEHOLDER_DESK_SERVICES
USING_REAL_BRANCH_REGISTRY: bool = _loaded_branches is not None

BRANCHES_BY_ID: dict[str, Branch] = {branch.branch_id: branch for branch in BRANCHES}

# Average minutes to service one ticket, per desk service. Used to convert a
# raw "people waiting" count into an estimated wait time when the SIGA page
# does not directly expose a wait-time figure, and as a fallback default for
# any of the real dataset's ~200 service labels not listed here explicitly.
# A handful of the most common real services are annotated for realism; the
# rest use DEFAULT_SERVICE_AVG_MINUTES.
DEFAULT_SERVICE_AVG_MINUTES = 10.0
SERVICE_AVG_MINUTES: dict[str, float] = {
    "Atendimento Geral": 8.0,
    "Cartão de Cidadão - Pedido/Renovação": 12.0,
    "Cartão de Cidadão - Levantamento": 5.0,
    "Cartão de Cidadão - Outros": 8.0,
    "Carta de Condução/ Driving License": 15.0,
    "Registo veículos - Pedido": 12.0,
    "Passaporte - Pedido": 15.0,
    "Passaporte - Levantamento / Inf.": 5.0,
    "Registo Predial - Certidões / Inf.": 10.0,
    "Registo Civil - Certidões / Inf.": 10.0,
    "Tesouraria": 6.0,
    "Execuções Fiscais": 18.0,
    "Marcação": 4.0,
    # Placeholder-registry service ids, kept so synthetic_bootstrap.py still
    # works when the real registry files are absent.
    "cartao_cidadao": 12.0,
    "financas": 15.0,
    "seguranca_social": 18.0,
    "registo_civil": 10.0,
    "iban_bancario": 8.0,
}

# Recurring annual tax deadlines as (month, day) tuples.
IRS_DEADLINE_MONTH_DAY: tuple[int, int] = (6, 30)
IMI_DEADLINE_MONTHS_DAYS: tuple[tuple[int, int], ...] = ((5, 31), (8, 31), (11, 30))

DEFAULT_DB_PATH = "data/queue_history.db"
DEFAULT_MODEL_PATH = "models/xgboost_wait_time.joblib"

# Baseline statistical fallback used when no model/feature data is available.
BASELINE_WAIT_MINUTES = 20.0
BASELINE_RAIN_MM = 0.0
BASELINE_ATTENDANCES = 10.0  # roughly the observed median daily attendances/store/service

REROUTE_RADIUS_KM = 15.0

# Fallback assumed business hours, used only when no real is_open signal is
# available (see NEAR_NOW_WINDOW_MINUTES below) — no real per-branch schedule
# data exists anywhere yet. Once scrapers/siga_scraper.py has accumulated
# enough real is_open observations per branch, this heuristic should be
# replaced with an actual observed schedule.
ASSUMED_BUSINESS_HOUR_START = 9
ASSUMED_BUSINESS_HOUR_END = 17
ASSUMED_BUSINESS_DAYS = frozenset({0, 1, 2, 3, 4})  # Mon-Fri, per datetime.weekday()

# Extra surge_level value (alongside "low"/"moderate"/"high"/"critical") used
# when the branch is known/assumed closed. Deliberately reuses the existing
# surge_level field rather than adding a new response field, so the
# /predict response schema (predicted_wait_minutes, surge_level,
# confidence_score, recommended_alternative_store) never changes shape.
SURGE_CLOSED_LABEL = "closed"

# "Latest known people_waiting" only means something for a "what's the queue
# like right now" request. If the requested prediction datetime is far from
# actual wall-clock now (a different hour of day, or a future/past date),
# reusing the single most-recent DB reading pairs a stale queue-state value
# with an unrelated hour_of_day/calendar context the model never saw
# together in training — an out-of-distribution combination that produces
# unstable, sometimes wildly extrapolated predictions (observed: negative
# and >2x-the-training-cap outputs for the same combo at different
# requested hours, all sharing one stale people_waiting reading). Beyond
# this window, people_waiting falls back to baseline instead.
NEAR_NOW_WINDOW_MINUTES = 60

# Real SIGA `tempoRealEspera` readings are sometimes wildly implausible —
# found 2026-07-27: 46% of "open" readings from one scheduled scrape showed
# 180-13,366 minutes, uncorrelated with the actual people_waiting count (many
# showed 0 people waiting alongside a 5-figure "wait"). Working hypothesis:
# the field may reflect elapsed idle time since the counter was last used,
# not a live computed wait — unconfirmed. A real physical queue cannot
# outlast a single business day before the branch closes and tickets reset,
# so anything above this is treated as implausible and excluded from the
# `estimated_wait_minutes` field used by training/API — but the untouched
# raw value is always kept in `raw_wait_time_minutes` so this can still be
# investigated later without having lost the original signal. Deliberately
# not reusing MAX_DERIVED_WAIT_MINUTES (180) here — that number was chosen
# for a synthetic queueing formula's assumptions, not a real-world constraint.
REAL_DATA_MAX_PLAUSIBLE_WAIT_MINUTES = 480

# --------------------------------------------------------------------------
# Wait-time proxy derivation (pipeline/demand_baseline.py)
#
# The real dados.gov.pt dataset has no desk-count or intra-day field, so
# converting its daily Atendimentos counts into an approximate wait_time_minutes
# requires assuming a number of parallel desks and a business-day length. These
# are documented simplifications, not measured facts — tune them if better
# information becomes available (e.g. per-store desk counts).
# --------------------------------------------------------------------------
DEFAULT_DESKS_PER_SERVICE = 3
OPERATING_HOURS_PER_DAY = 8.0
MAX_DERIVED_WAIT_MINUTES = 180.0

# A single flat desk count badly understates capacity for the handful of
# real combos with extreme volume (some real branch/service pairs exceed
# 900 attendances/day for one service) — pipeline/demand_baseline.py scales
# the assumed desk count up with real daily volume and this service's own
# avg_service_minutes (see estimate_desks_for_volume), using DEFAULT_DESKS_PER_SERVICE
# only as a floor for low-volume combos. TARGET_DESK_UTILIZATION is the
# sustainable fraction of full capacity a desk is assumed to run at.
TARGET_DESK_UTILIZATION = 0.7

# --------------------------------------------------------------------------
# Intraday expansion for derived proxy rows (pipeline/demand_baseline.py)
#
# The real dataset has no intra-day timestamp, so anchoring every daily
# proxy row at one flat clock time would give `hour_of_day` zero variance
# across the entire proxy dataset. Instead each day is expanded into a few
# representative daypart snapshots: (hour, minute, volume_factor), where
# volume_factor scales the day's average hourly attendance rate (factors
# average to 1.0 across a "typical" day). Each snapshot's wait-time estimate
# uses SNAPSHOT_WINDOW_HOURS (~1 hour), not the full day, as the M/M/1
# capacity window, since a snapshot represents an hour-scale slice of
# demand, not the whole day's total — reusing the full-day operating-hours
# constant here would make capacity look ~8x too large and understate wait
# times at every snapshot.
# --------------------------------------------------------------------------
DIURNAL_SNAPSHOTS: tuple[tuple[int, int, float], ...] = (
    (9, 30, 0.8),   # morning
    (12, 30, 1.4),  # midday peak
    (15, 30, 0.8),  # afternoon
)
SNAPSHOT_WINDOW_HOURS = 1.0

# --------------------------------------------------------------------------
# Proxy-vs-live sample weighting (pipeline/train.py)
#
# Once live SIGA scraping accumulates real samples for a given
# (branch_id, desk_service_id), that combo's historical_derived_proxy rows
# should count for less during training — but a global "drop all proxy data"
# cutover is wrong: real coverage will be extremely uneven across ~2,000
# distinct combos, so a global switch would blind whichever combos haven't
# accumulated live data yet. Instead each proxy row's weight decays per its
# own combo's live sample count: w = 1 / (1 + alpha * live_count). At
# live_count=0 (true today — no live scraping has run yet) w=1.0, i.e. this
# is a no-op until live data actually exists.
# --------------------------------------------------------------------------
PROXY_WEIGHT_DECAY_ALPHA = 0.05
